name: deploy

on:
  workflow_call:

env:
  PROJECT_PATCH: src/AllSales.Console/AllSales.Console.csproj

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATCH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATCH }} -c Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATCH }} --configuration Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AllSales'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        package: ${{env.DOTNET_ROOT}}/myapp